/**
 * Curated seed list of ~150 company slugs across Greenhouse, Lever, and Ashby.
 * Used by run_setup to discover which companies have active job boards.
 * Slugs are the URL identifier each ATS uses for the company's careers page.
 */

export interface SeedEntry {
  slug: string;
  ats: "greenhouse" | "lever" | "ashby";
}

export const SEED_LIST: SeedEntry[] = [
  // ── Greenhouse ──────────────────────────────────────
  { slug: "anthropic", ats: "greenhouse" },
  { slug: "openai", ats: "greenhouse" },
  { slug: "stripe", ats: "greenhouse" },
  { slug: "airbnb", ats: "greenhouse" },
  { slug: "coinbase", ats: "greenhouse" },
  { slug: "figma", ats: "greenhouse" },
  { slug: "notion", ats: "greenhouse" },
  { slug: "airtable", ats: "greenhouse" },
  { slug: "plaid", ats: "greenhouse" },
  { slug: "databricks", ats: "greenhouse" },
  { slug: "discord", ats: "greenhouse" },
  { slug: "duolingo", ats: "greenhouse" },
  { slug: "gusto", ats: "greenhouse" },
  { slug: "flexport", ats: "greenhouse" },
  { slug: "cockroachlabs", ats: "greenhouse" },
  { slug: "hashicorp", ats: "greenhouse" },
  { slug: "gitlab", ats: "greenhouse" },
  { slug: "brex", ats: "greenhouse" },
  { slug: "retool", ats: "greenhouse" },
  { slug: "benchling", ats: "greenhouse" },
  { slug: "vanta", ats: "greenhouse" },
  { slug: "ramp", ats: "greenhouse" },
  { slug: "navan", ats: "greenhouse" },
  { slug: "anduril", ats: "greenhouse" },
  { slug: "scaleai", ats: "greenhouse" },
  { slug: "watershedclimate", ats: "greenhouse" },
  { slug: "dbtlabsinc", ats: "greenhouse" },
  { slug: "snyk", ats: "greenhouse" },
  { slug: "relativityspace", ats: "greenhouse" },
  { slug: "verkada", ats: "greenhouse" },
  { slug: "celonis", ats: "greenhouse" },
  { slug: "rubrik", ats: "greenhouse" },
  { slug: "wiz", ats: "greenhouse" },
  { slug: "coreweave", ats: "greenhouse" },
  { slug: "crusoeenergy", ats: "greenhouse" },
  { slug: "chime", ats: "greenhouse" },
  { slug: "navan", ats: "greenhouse" },
  { slug: "podium81", ats: "greenhouse" },
  { slug: "carta", ats: "greenhouse" },
  { slug: "ironclad", ats: "greenhouse" },
  { slug: "zapier", ats: "greenhouse" },
  { slug: "lattice", ats: "greenhouse" },
  { slug: "samsara", ats: "greenhouse" },
  { slug: "mux", ats: "greenhouse" },
  { slug: "nerdwallet", ats: "greenhouse" },
  { slug: "pagerduty", ats: "greenhouse" },
  { slug: "iterable", ats: "greenhouse" },
  { slug: "webflow", ats: "greenhouse" },
  { slug: "postman", ats: "greenhouse" },
  { slug: "linear", ats: "greenhouse" },

  // ── Lever ───────────────────────────────────────────
  { slug: "netflix", ats: "lever" },
  { slug: "spotify", ats: "lever" },
  { slug: "figma", ats: "lever" },
  { slug: "cloudflare", ats: "lever" },
  { slug: "reddit", ats: "lever" },
  { slug: "datadog", ats: "lever" },
  { slug: "elastic", ats: "lever" },
  { slug: "sourcegraph", ats: "lever" },
  { slug: "tailscale", ats: "lever" },
  { slug: "fly", ats: "lever" },
  { slug: "vercel", ats: "lever" },
  { slug: "supabase", ats: "lever" },
  { slug: "planetscale", ats: "lever" },
  { slug: "render", ats: "lever" },
  { slug: "railway", ats: "lever" },
  { slug: "replit", ats: "lever" },
  { slug: "deno", ats: "lever" },
  { slug: "netlify", ats: "lever" },
  { slug: "temporal-technologies", ats: "lever" },
  { slug: "prefect", ats: "lever" },
  { slug: "dagster", ats: "lever" },
  { slug: "airbyte", ats: "lever" },
  { slug: "fivetran", ats: "lever" },
  { slug: "materialize", ats: "lever" },
  { slug: "stytch", ats: "lever" },
  { slug: "hex", ats: "lever" },
  { slug: "prisma", ats: "lever" },
  { slug: "grafana", ats: "lever" },
  { slug: "pulumi", ats: "lever" },
  { slug: "snyk", ats: "lever" },
  { slug: "miro", ats: "lever" },
  { slug: "coda", ats: "lever" },
  { slug: "loom", ats: "lever" },
  { slug: "mercury", ats: "lever" },
  { slug: "pipe", ats: "lever" },
  { slug: "superhuman", ats: "lever" },
  { slug: "resend", ats: "lever" },
  { slug: "axiom-co", ats: "lever" },
  { slug: "turso", ats: "lever" },
  { slug: "neon", ats: "lever" },
  { slug: "convex", ats: "lever" },
  { slug: "modal", ats: "lever" },
  { slug: "replicate", ats: "lever" },
  { slug: "huggingface", ats: "lever" },
  { slug: "cohere", ats: "lever" },
  { slug: "mistral", ats: "lever" },
  { slug: "langchain", ats: "lever" },
  { slug: "weights-and-biases", ats: "lever" },
  { slug: "anyscale", ats: "lever" },
  { slug: "together-ai", ats: "lever" },
  { slug: "perplexity-ai", ats: "lever" },
  { slug: "cursor", ats: "lever" },

  // ── Ashby ───────────────────────────────────────────
  { slug: "anthropic", ats: "ashby" },
  { slug: "vercel", ats: "ashby" },
  { slug: "linear", ats: "ashby" },
  { slug: "ramp", ats: "ashby" },
  { slug: "notion", ats: "ashby" },
  { slug: "retool", ats: "ashby" },
  { slug: "clerk", ats: "ashby" },
  { slug: "resend", ats: "ashby" },
  { slug: "inngest", ats: "ashby" },
  { slug: "turso", ats: "ashby" },
  { slug: "neon", ats: "ashby" },
  { slug: "dagger", ats: "ashby" },
  { slug: "val-town", ats: "ashby" },
  { slug: "raycast", ats: "ashby" },
  { slug: "cal", ats: "ashby" },
  { slug: "mintlify", ats: "ashby" },
  { slug: "tinybird", ats: "ashby" },
  { slug: "highlight", ats: "ashby" },
  { slug: "knock", ats: "ashby" },
  { slug: "trigger", ats: "ashby" },
  { slug: "baseten", ats: "ashby" },
  { slug: "fireworks-ai", ats: "ashby" },
  { slug: "cerebras", ats: "ashby" },
  { slug: "groq", ats: "ashby" },
  { slug: "cohere", ats: "ashby" },
  { slug: "stability-ai", ats: "ashby" },
  { slug: "adept", ats: "ashby" },
  { slug: "character-ai", ats: "ashby" },
  { slug: "inflection-ai", ats: "ashby" },
  { slug: "ai21labs", ats: "ashby" },
  { slug: "deepmind", ats: "ashby" },
  { slug: "midjourney", ats: "ashby" },
  { slug: "pika", ats: "ashby" },
  { slug: "runway", ats: "ashby" },
  { slug: "eleven-labs", ats: "ashby" },
  { slug: "jasper-ai", ats: "ashby" },
  { slug: "copy-ai", ats: "ashby" },
  { slug: "arcee-ai", ats: "ashby" },
  { slug: "poolside", ats: "ashby" },
  { slug: "magic-dev", ats: "ashby" },
  { slug: "glean", ats: "ashby" },
];
